In [ ]:
# implemented and written by Yeoreum Lee in AI HnV Lab @ Sahmyook University in 2023
__author__ = 'leeyeoreum02'

In [1]:
from typing import Tuple, Callable

import numpy as np
import pandas as pd

### 1. 데이터 불러오기

메인 교재와 서브 강의만을 활용하여 pandas로 MNIST 데이터셋을 불러오시오. [mnist_train.csv, mnist_test.csv] (구글링 금지)

In [2]:
...

print(train_data.shape, test_data.shape)
train_data.head()

(60000, 785) (10000, 785)


label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      4    0    0    0    0    0    0    0    0    0  ...      0      0   
3      1    0    0    0    0    0    0    0    0    0  ...      0      0   
4      9    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [3]:
# shuffle
train_data = ...

print(train_data.shape, test_data.shape)
train_data.head()

(60000, 785) (10000, 785)


label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
44937      4    0    0    0    0    0    0    0    0    0  ...      0      0   
21314      0    0    0    0    0    0    0    0    0    0  ...      0      0   
45397      7    0    0    0    0    0    0    0    0    0  ...      0      0   
9497       6    0    0    0    0    0    0    0    0    0  ...      0      0   
6093       8    0    0    0    0    0    0    0    0    0  ...      0      0   

       28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
44937      0      0      0      0      0      0      0      0  
21314      0      0      0      0      0      0      0      0  
45397      0      0      0      0      0      0      0      0  
9497       0      0      0      0      0      0      0      0  
6093       0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

### 2. 데이터 나누기(split)

메인 교재와 서브 강의만을 이용하여 data를 feature와 정답(label)로 나누는 코드를 구현하시오. (구글링 금지)


In [4]:
def split_data(train_data: pd.DataFrame, test_data: pd.DataFrame) -> Tuple[np.ndarray]:
    ...
    return train_x_data, train_t_data, test_x_data, test_t_data


train_x_data, train_t_data, test_x_data, test_t_data = split_data(train_data, test_data)
print(train_x_data.shape, train_t_data.shape, test_x_data.shape, test_t_data.shape,)

(60000, 784) (60000,) (10000, 784) (10000,)


### 3. 데이터 전처리(preprocessing)

a. 메인 교재와 서브 강의를 활용하여 train data를 normalize하시오. (구글링 가능)

$$normalize(X) = \frac {X - min} {max - min} \space (max - min \neq 0)$$

b. 메인 교재와 서브 강의를 활용하여 test data를 one-hot encoding하시오. (구글링 가능)

In [5]:
def preprocess(train_x_data: np.ndarray, train_t_data: np.ndarray, test_x_data: np.ndarray, test_t_data: np.ndarray) -> Tuple[np.ndarray]:
    ...
    return train_x_data, train_t_data_onehot, test_x_data, test_t_data_onehot

    
train_x_data, train_t_data_onehot, test_x_data, test_t_data_onehot = preprocess(train_x_data, train_t_data, test_x_data, test_t_data)
print(train_t_data_onehot[:5])
print(train_x_data.shape, train_t_data_onehot.shape, test_x_data.shape, test_t_data_onehot.shape)

[[0.01 0.01 0.01 0.01 0.99 0.01 0.01 0.01 0.01 0.01]
 [0.99 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01]
 [0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.99 0.01 0.01]
 [0.01 0.01 0.01 0.01 0.01 0.01 0.99 0.01 0.01 0.01]
 [0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.99 0.01]]
(60000, 784) (60000, 10) (10000, 784) (10000, 10)


### 4. 활성 함수(activation function)

메인 교재와 서브 강의만을 이용하여 활성 함수 중 하나인 softmax 함수를 구현하시오. (구글링 금지)

$$\sigma(\boldsymbol{z})_{i} = \frac {e^{z_{i}}} {\sum_{i=1} ^K e^{z_{i}}}$$

In [6]:
def sigmoid(x: np.ndarray) -> np.ndarray:
    return 1 / (1 + np.exp(-x))

def softmax(z: np.ndarray) -> np.ndarray:
    return ...

### 5. 신경망(neural network) 모델

메인 교재와 서브 강의만을 이용하여 신경망(neural network) 모델을 구현하시오. (구글링 금지)

$$f(W^{(2)}, b^{(2)})(\boldsymbol{x}) = sigmoid(W^{(2)}\boldsymbol{x} + b^{(2)})$$
$$g(W^{(3)}, b^{(3)})(\boldsymbol{x}) = \sigma(W^{(3)}\boldsymbol{x} + b^{(3)})$$
$$
\begin{matrix}
y &=& h(W^{(2)}, b^{(2)}, W^{(3)}, b^{(3)})(\boldsymbol{x}) \\
  &=& (g(W^{(3)}, b^{(3)}) \circ f(W^{(2)}, b^{(2)}))(\boldsymbol{x}) \\
  &=& g(W^{(3)}, b^{(3)})(f(W^{(2)}, b^{(2)})(\boldsymbol{x})) \\
  &=& \sigma(W^{(3)}sigmoid(W^{(2)}\boldsymbol{x} + b^{(2)}) + b^{(3)})
\end{matrix}
$$

In [19]:
class NeuralNetwork:
    def __init__(self, n_input: int, n_output: int, n_hidden: int = 128) -> None:
        ...
        
    def forward(self, x: np.ndarray) -> np.ndarray:
        ...
        return y

    def __call__(self, x: np.ndarray) -> np.ndarray:
        return self.forward(x)
    
    
model = NeuralNetwork(n_input=..., n_output=...)

### 6. 오차 함수 (error function, loss function)

주어진 수식만을 이용하여 CE(cross entropy) 오차 함수를 구현하시오. (구글링, 메인 교재 참고, 서브 강의 참고 금지)
- delta는 log의 진수 조건을 만족하기 위해 필요하므로 반드시 사용
- N은 데이터 개수 (행 개수)
- $y$는 정답(label) $\hat{y}$은 예측값(prediction)

$$CE = -\sum_{i=1} ^N (\boldsymbol{y_{i}} \cdot \log \boldsymbol{\hat{y_{i}}} + (1 - \boldsymbol{y_{i}}) \cdot \log (1 - \boldsymbol{\hat{y_{i}}}))$$

In [8]:
def cross_entropy_loss(y_data: np.ndarray, t_data: np.ndarray) -> np.ndarray:
    delta = 1e-4
    return ...

### 7. 편미분 함수 (partial numerical derivative)

- n은 input node 개수, m은 hidden node 개수, o는 output node 개수

$$J(W^{(2)}) = \frac{dE} {dW^{(2)}} = \begin{pmatrix} 
\frac{\partial E} {\partial W^{(2)}_{11}} & \cdots & \frac {\partial E} {\partial W^{(2)}_{m1}} \\
\vdots & \ddots & \vdots \\ 
\frac {\partial E} {\partial W^{(2)}_{1n}} & \cdots & \frac {\partial E} {\partial W^{(2)}_{mn}} \end{pmatrix}$$

$$J(W^{(3)}) = \frac{dE} {dW^{(3)}} = \begin{pmatrix} 
\frac{\partial E} {\partial W^{(3)}_{11}} & \cdots & \frac {\partial E} {\partial W^{(3)}_{o1}} \\
\vdots & \ddots & \vdots \\ 
\frac {\partial E} {\partial W^{(3)}_{1m}} & \cdots & \frac {\partial E} {\partial W^{(3)}_{om}} \end{pmatrix}$$

$$J(\boldsymbol{b^{(2)}}) = \frac{dE} {d\boldsymbol{b^{(2)}}} = \begin{pmatrix} \frac{\partial E} {\partial b^{(2)}_{1}} \frac{\partial E} {\partial b^{(2)}_{2}} \end{pmatrix}$$

$$J(\boldsymbol{b^{(3)}}) = \frac{dE} {d\boldsymbol{b^{(3)}}} = \begin{pmatrix} \frac{\partial E} {\partial b^{(3)}_{1}} \frac{\partial E} {\partial b^{(3)}_{2}} \end{pmatrix}$$

In [9]:
def numerical_derivative(f: Callable, x: np.ndarray) -> np.ndarray:
    h = 1e-4
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        temp = x[idx]
        x[idx] = float(temp) + h
        fx1 = f(x)
        
        x[idx] = temp - h
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2 * h)
        
        x[idx] = temp
        it.iternext()
        
    return grad

### 8-1. 모델 학습 (train)

메인 교재와 서브 강의만을 이용하여 다음 순서를 가지는 학습 코드를 구현하시오. (구글링 금지)
- 한꺼번에 다 학습 -> batch(뭉텅이) gradient descent

1. 모델 순전파 (forward)
2. 오차 계산 (loss)
3. 모델 파라미터(가중치 + 편향) 별 오차 함수의 편미분값 계산 (numerical derivative)
4. 가중치(weight), 편향(bias) 갱신 (경사 하강법, gradient descent)

In [10]:
def train_batch() -> None:
    ...


train_batch()

KeyboardInterrupt: 

### 8-2. 모델 학습 (train)

메인 교재와 서브 강의만을 이용하여 다음 순서를 가지는 학습 코드를 구현하시오. (구글링 금지)
- mini-batch 단위로 학습 -> mini-batch gradient descent
- 만약 batch size가 1인 경우 -> stocastic gradient descent
- 메모리가 부족해 한꺼번에 다 안들어갈 경우 위의 방식들을 사용
- 여기선 메모리가 부족하진 않지만 loss 변화가 너무 늦게 출력되니까 사용

1. 모델 순전파 (forward)
2. 오차 계산 (loss)
3. 모델 파라미터(가중치 + 편향) 별 오차 함수의 편미분값 계산 (numerical derivative)
4. 가중치(weight), 편향(bias) 갱신 (경사 하강법, gradient descent)

In [20]:
def train_mini_batch() -> None:
    ...
                
                
train_mini_batch()

Epoch: 0, step: 0, loss 9.542098089816562
Epoch: 0, step: 1, loss 1.6276390972015258
Epoch: 0, step: 2, loss 9.616006131579352
Epoch: 0, step: 3, loss 9.033076191087133
Epoch: 0, step: 4, loss 9.424084911879163
Epoch: 0, step: 5, loss 6.9276291235833725
Epoch: 0, step: 6, loss 6.592219003785746
Epoch: 0, step: 7, loss 2.203215612282584
Epoch: 0, step: 8, loss 9.779394345529438
Epoch: 0, step: 9, loss 6.306510581809841
Epoch: 0, step: 10, loss 2.5358057511827763
Epoch: 0, step: 11, loss 9.691672894323363
Epoch: 0, step: 12, loss 6.7438864728623455
Epoch: 0, step: 13, loss 9.582851387735955
Epoch: 0, step: 14, loss 2.4749930989396103
Epoch: 0, step: 15, loss 4.995239615196154
Epoch: 0, step: 16, loss 9.810783816020272
Epoch: 0, step: 17, loss 9.686294035542304
Epoch: 0, step: 18, loss 7.5193177098430874
Epoch: 0, step: 19, loss 9.768022746390415
Epoch: 0, step: 20, loss 9.12719436307242
Epoch: 0, step: 21, loss 9.854966302923193
Epoch: 0, step: 22, loss 9.642742929994151
Epoch: 0, step: 